server:
  port: 8004
spring:
  application:
    name: service-cms
  #mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.89.177.244:3306/education?useUnicode=true&characterEncoding=UTF-8
    password: 22446688
    username: root
  #redis数据库连接设置
  redis:
    host: 121.89.177.244
    port: 6379
    database: 0
    timeout: 1800000
    password: 22446688
    lettuce:
      pool:
        max-active: 20
        max-wait: 1
        #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0
  #返回的json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    #  nacos注册
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#  <!--#配置mapper xml文件路径-->,必须pom.xml进行配置后使用
mybatis-plus:
  mapper-locations: classpath:com/plxcc/cms/mapper/xml/*.xml  #xml的路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl